version: 1
disable_existing_loggers: false
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    "()": uvicorn.logging.AccessFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  default:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: default
    filename: c:\container_byda\logs\default.log
    when: 'midnight'
    interval: 1
    backupCount: 20
    encoding: utf8
  access:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: access
    filename: c:\container_byda\logs\access.log
    when: 'midnight'
    interval: 1
    backupCount: 20
    encoding: utf8
  apiserver:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: default
    filename: c:\container_byda\logs\server.log
    when: 'midnight'
    interval: 1
    backupCount: 20
    encoding: utf8
loggers:
  fastapi:
    level: INFO
    handlers:
      - apiserver
    propagate: no
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no